site_name: "pymsgbus"

theme:
  name: "readthedocs"

nav:
  - Home: index.md
  - Definitions: types.md
  - Publisher and Subscribers: pubsub.md
  - Producers and Consumers: consumers.md
  - Events: events.md
  - Services: services.md
  - Unit Of Work: sessions.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: "google"  # or "restructuredtext"